/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

let fib = [0, 1];
let sumOfEvenIntegers = 0;
var fibonacci = function(num) {
  for (var i = 2; i < num; i++) {
    fib.push(fib[i-2]+fib[i-1]);
    if (fib[i]%2 === 0 && fib[i] < 4000000) {
      sumOfEvenIntegers+=fib[i];
    }
  }
  console.log(fib);
  console.log("The sum is "+ sumOfEvenIntegers);
}

fibonacci(20);
